#set WOLFRAMRTL_INCLUDE_DIR

if(RE_BUILD)
	if(SYSTEMID STREQUAL "iOS")
		if(BUILD_PLATFORM MATCHES "iossimulator.*")
			set(WOLFRAM_LIBRARY_PATH "$ENV{IOSSIMULATOR_WOLFRAMRTL_DIR}" CACHE STRING "")
		else()
			set(WOLFRAM_LIBRARY_PATH "$ENV{IOS_WOLFRAMRTL_DIR}" CACHE STRING "")
		endif()
	elseif(SYSTEMID STREQUAL "visionOS")
		if(BUILD_PLATFORM MATCHES "visionossimulator.*")
			set(WOLFRAM_LIBRARY_PATH "$ENV{VISIONOSSIMULATOR_WOLFRAMRTL_DIR}" CACHE STRING "")
		else()
			set(WOLFRAM_LIBRARY_PATH "$ENV{VISIONOS_WOLFRAMRTL_DIR}" CACHE STRING "")
		endif()
	endif()
elseif(NOT WOLFRAM_LIBRARY_PATH)
	# TEAMCITY_SYSTEMID
	if(NOT EXISTS "${CMAKE_BINARY_DIR}/RuntimeLibrary/${SYSTEMID}/WolframLibrary.h"
		AND 
		NOT EXISTS "${CMAKE_BINARY_DIR}/RuntimeLibrary/WolframRTL.framework/Headers/WolframLibrary.h)")

		include(${CMAKE_CURRENT_LIST_DIR}/../Downloads.cmake)

		download_RuntimeLibrary("${CMAKE_BINARY_DIR}/RuntimeLibrary" "master")
	endif()
	
	if(SYSTEMID STREQUAL "iOS" OR SYSTEMID STREQUAL "visionOS")
		set(WOLFRAM_LIBRARY_PATH "${CMAKE_BINARY_DIR}/RuntimeLibrary" CACHE PATH "")
	else()
		set(WOLFRAM_LIBRARY_PATH "${CMAKE_BINARY_DIR}/RuntimeLibrary/${SYSTEMID}" CACHE PATH "")
	endif()
endif()
message("WOLFRAM_LIBRARY_PATH : ${WOLFRAM_LIBRARY_PATH}")

if(SYSTEMID STREQUAL "iOS" OR SYSTEMID STREQUAL "visionOS")
	set(WOLFRAMRTL_INCLUDE_DIR ${WOLFRAM_LIBRARY_PATH}/WolframRTL.framework/Headers CACHE STRING "")
else()
	set(WOLFRAMRTL_INCLUDE_DIR ${WOLFRAM_LIBRARY_PATH} CACHE STRING "")
endif()

if(NOT IS_DIRECTORY ${WOLFRAMRTL_INCLUDE_DIR})
	message(FATAL_ERROR "WOLFRAMRTL_INCLUDE_DIR : ${WOLFRAMRTL_INCLUDE_DIR} is not a directory")
endif()

message("WOLFRAMRTL_INCLUDE_DIR : ${WOLFRAMRTL_INCLUDE_DIR}")


